### ISSUE TITLE
I think that black is a good colour!

### ISSUE THREAD

**Issue by osmart** [CharlesNunn001/ARU-Example-Repo#3]
And
https://en.wikipedia.org/wiki/Black_Square_(painting)
is the best painting ever!

The poem would be much improved by mentioning black.

Will fork your repo and suggest an improvement.

**Comment by CharlesNunn001** [comment]
Hi osmart,

Are my changes ok?

**Comment by osmart** [comment]
> Hi osmart,
> 
> Are my changes ok?

Changes are great thanks for fixing my poor spelllling

**Comment by CharlesNunn001** [comment]
Changes Merged
